### ISSUE TITLE
Keyboard accessibility appears to be broken

### ISSUE THREAD

**Issue by scriby** [ghinda/css-toggle-switch#39]
I can't seem to use the keyboard to manipulate the toggle switches on the demo site. The inputs don't seem to be in the tab order, and the only thing hit is the anchor.

**Comment by ghinda** [comment]
That's weird. It works for me on Chrome.
What browser are you using? Are you testing on the main page (https://ghinda.net/css-toggle-switch/)?

**Comment by scriby** [comment]
I'm using Chrome, and here's a video of what I'm seeing: http://screencast.com/t/GGR1cMft

If they were normal radio buttons, the focus would have landed on each of the options, right?

**Comment by scriby** [comment]
Ah, I see... with radios the tab key only hits the first item, then you have to use the arrow keys to move around. I guess that works ok for screen readers, but it's a little strange for sighted users since it doesn't "look" like a radio button.

**Comment by ghinda** [comment]
That's right. It's because the `switch-toggle` uses `radio` inputs, which act act a single element, because they have the same `name` and a single value.

http://www.w3.org/wiki/RadioButton

The only way I can think of right now, to get the functionality you describe is to use different `name`s for the radio inputs and use js to change the value of each of them in the "group". It's very hacky.
